repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8  # or the version you use

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the most recent flake8 version
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1  # Use the most recent mypy version
    hooks:
      - id: mypy
        additional_dependencies: [types-tensorflow]  # If you use requests, for example
        exclude: '(paper)'
