name: Python CI

on:
  push:
    branches: [ main, dev-emulator]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install code quality dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[quality] # 'quality' extra defined in setup.py
    - name: Install test dependencies
      run: |
        pip install -e .[test]  # 'test' extra defined in setup.py
    - name: Run quality checks
      run: |
        # Run formatting check
        black --check .

        # Run linting
        flake8 .

        # Run type checking on DeepGlow package
        mypy DeepGlow/ 
    - name: Test with pytest
      run: |
        pytest

